### ISSUE TITLE
What about a single column design?

### ISSUE THREAD

**Issue by Moosems** [Akuli/kauppalista#6]
What about a single-column design with a top section for to-do and a bottom for bought items? I think it might look nicer on mobile this way.

**Comment by Akuli** [comment]
The UI must fit a lot of items, e.g. my parents keep more than 100 items on the "Bought" side and drag them to the other side when they are planning to buy them. Less vertical space would make that a hell to scroll through.

**Comment by Moosems** [comment]
Maybe side to side scrolling for mobile (similar to Trello)?

**Comment by Akuli** [comment]
I don't really see why you wouldn't just use Trello if you want side to side scrolling, or in general, something more advanced than this project. This project's UI is even simpler than Trello, ideal for making a simple task list, such as a shopping list.

**Comment by Moosems** [comment]
Mostly because I prefer using your stuff where possible :).
